### ISSUE TITLE
Any plans to have a "submitting" state?

### ISSUE THREAD

**Issue by billyxs** [alsiola/form-and-function#11]
When submitting a form that has some processing time, it would be useful to have a `submitting` state to trigger animations, disable buttons, etc.  Any plans to provide that, or do you have preferred way that this should handled outside of `form-and-function`?

Thanks for the project!

**Comment by alsiola** [comment]
Hi @billyxs, I agree this would be useful.  There isn't any way to do it within the library currently, but it should be supported pretty easily.  I'll try and get something into the next release.  No solid timeframe but hopefully the next week or two.

**Comment by billyxs** [comment]
Very cool.  Thanks @alsiola
